#!/bin/bash
# Refreshes the bundled Public Suffix List (publicsuffix.org, maintained by Mozilla); install.sh runs it before a release.
# It is what tells "acme.co.uk" apart from "co.uk" and "evil.pages.dev" apart from "pages.dev".
set -euo pipefail
cd "$(dirname "$0")/.."
LIST=$(curl -fsSL https://publicsuffix.org/list/public_suffix_list.dat | grep -vE '^(//|[[:space:]]*$)' | sed 's/[[:space:]].*//')
# A captive portal or error page would replace the list with junk.
if [ "$(echo "$LIST" | wc -l)" -lt 5000 ] || ! grep -qx 'co\.uk' <<< "$LIST"; then
    echo "The download doesn't look like the Public Suffix List." >&2; exit 1
fi
{
    echo "// Generated by scripts/update-psl.sh; do not edit."
    echo "// Public Suffix List, https://publicsuffix.org, under the Mozilla Public License 2.0 (https://mozilla.org/MPL/2.0/)."
    echo "extension PublicSuffix {"
    echo "    static let list = #\"\"\""
    echo "$LIST"
    echo "\"\"\"#"
    echo "}"
} > Sources/CodeCatchCore/PublicSuffixList.swift
echo "$(echo "$LIST" | wc -l | tr -d ' ') rules"
